### PR TITLE
Added typescript definition file, exported UnauthorizedError

### PR DESCRIPTION
**Pull request by Root-Core**
Added type definition file for typescript. #101

Exported UnauthorizedError, as it could be used by developers in the "connection" event in order to prevent users access. (Augment the function of this middleware)

Added @types/socket.io as dependency.
I would appreciate some feedback, as i am no expert in typescript definition files.

### CODE REVIEW

**Comment by kzay** [comment]
Guy , please merge this PR. We need Typescript definition

**Comment by Root-Core** [comment]
This is no longer supported.
You should check out my fork: https://github.com/Root-Core/socketio-jwt

**Comment by beardaway** [comment]
Hey everyone!

Terribly sorry for such delay in response! At the time the tool hosted in the repo was developed we didn't have enough bandwidth to implement it further that's why we kinda decided to "outsource" it to our community developers.

For now we are gradually expanding the team and we're aiming that at some point in the future we'll be able to maintain and develop this repo more effectively. Sorry for any inconvenience!

**Comment by Root-Core** [comment]
@beardaway This PR should be reopened / merged, as it does not change the functionality at all. It just allows TypeScript devs to use this in a TypeScript way.

**Pull request merged**
