### PR TITLE
Cherrypicked commits of #105 by matwithonet1

### PR DESCRIPTION
**Pull request by Root-Core**
This is a followup of #105

Changes by @matwithonet1, Andrew Kutta, @mikebeyer:
- Improved test coverage
- Documentation of Authorization Header
- Restricting Authorization to only Header Support
- Linting
- Node 0.10 compatibility
- Updated Deps
- etc..

Additional changes by @Root-Core:
- Some Deps were devDeps
- Whitespaces / Formatting
- Code-Smells
- Little bug fixes (mostly merge errors)
- Improved readme
- etc..

I have not tested the changes after https://github.com/auth0-community/auth0-socketio-jwt/commit/27aaab31616d103e6907c4a35aceaa972dde2684 in production yet, but reviewed them. Looks good.

### CODE REVIEW

**Comment by akutta** [comment]
@Root-Core if you would like to have this merged in, I will work on getting mergeable.  I would prefer if my team did not need to use our forked version of this.

**Comment by Root-Core** [comment]
@beardaway This PR has been fixed and should be merged in. The ci does fail, because `jsonwebtoken` dropped support for node < 4 a while ago. `npm test` is passing.

@akutta The current state of this PR should work for your team. If it doesn't, let me know.

**Comment by Root-Core** [comment]
I have updated travis to test against node version 4, 8, 10, 12 and newest (as 4 is supported by jsonwebtoken and 8, 10, 12 as they are still supported and maintained by nodejs).

I also updated the code a bit and implemented a workaround for `let` with node 4.

**Comment by beardaway** [comment]
Thanks a lot for all the contributions @Root-Core !

**Pull request merged**
