### PR TITLE
Fix authentication for namespaces #95

### LINKED ISSUE #95: Namespace authentication not working with multiplexing
Hello,

I encountered an issue, while implementing authentication over socketio.

I am using the main namespace ('/') to login an client.
This works great, but as I have to secure all other namespaces, there are some issues.

By the way I am using the handshake via. query, but had to deactivate `multiplex` in order to get it working properly. @nhahn has experienced the same problem regarding his post in #32. ([Comment](https://github.com/auth0/socketio-jwt/issues/32#issuecomment-133641125))

He guesses, it would be an issue with socketio not passing the query string to the middleware.
So is this an issue with socketio, or socketio-jwt?

Regards, Root-Core.

### PR DESCRIPTION
**Pull request by Root-Core**
Try to get the token from query string, which is stored in the sockets "handshake" object.

This should fix #95 and be a more elegant (say valid) approach.

### CODE REVIEW

**Comment by dolftax** [comment]
Guys, any update on this?

**Comment by Root-Core** [comment]
@dolftax I have forked this project, to do some changes right now.

Just have a look at [this](https://github.com/Root-Core/socketio-jwt) and keep in mind, that you can install forks straight from Git via NPM like a boss. ;)

**Comment by dolftax** [comment]
Thanks man. Tag me in issues if you need help. Will contribute when I find time.

**Comment by Root-Core** [comment]
@beardaway 
I have not checked the current status of the project, but it seems that this patch  (or another solution for #95) is not applied by now. You really should consider review this PR.

**Comment by Root-Core** [comment]
@beardaway Thank you for maintaining and accepting the pull requests! ❤️
It would be nice, if you could reopen this PR, to prevent it from getting lost.

**Comment by Root-Core** [comment]
Fixed merge conflict, should be good to go.

**Pull request merged**
